package com.spring.jdbc.dao;

import com.spring.jdbc.entities.TimestampEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.Types;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@Repository("timestampDao")
public class TimestampDAOImpl implements TimestampDAO {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private NamedParameterJdbcTemplate namedJdbcTemplate;

    // 1. Insert and capture the Auto-Generated ID
    @Override
    public int insertAndReturnId(TimestampEntity entity) {
        String sql = "INSERT INTO example_timestamp (DATA, CUR_TIMESTAMP) " +
                "VALUES (:data, :ts)";

        MapSqlParameterSource params = new MapSqlParameterSource()
                .addValue("data", entity.getData(), Types.VARCHAR)
                .addValue("ts", entity.getCur_timestamp(), Types.TIMESTAMP);

        // This acts as a "bucket." When the database finishes the insert, it sends back a special response containing
        // the new ID. Spring catches that ID and stores it in this object.
        GeneratedKeyHolder keyHolder = new GeneratedKeyHolder();

        namedJdbcTemplate.update(sql, params, keyHolder);

        // Retrieves the ID generated by MySQL/H2/Postgres
        int id = Objects.requireNonNull(keyHolder.getKey()).intValue();
        return id;

    }

    // 2. Performance Batching: Chunked Inserts
    @Override
    public void insertInChunks(List<TimestampEntity> entities, int chunkSize) {
        String sql = "INSERT INTO example_timestamp (DATA, CUR_TIMESTAMP) VALUES (:data, :timestamp)";

        for (int i = 0; i < entities.size(); i += chunkSize) {
            List<TimestampEntity> chunk = entities.subList(i, Math.min(i + chunkSize, entities.size()));

            SqlParameterSource[] batch = chunk.stream()
                    .map(entity -> new MapSqlParameterSource()
                            .addValue("data", entity.getData(), Types.VARCHAR)
                            .addValue("timestamp", entity.getCur_timestamp(), Types.TIMESTAMP))
                    .toArray(SqlParameterSource[]::new);

            int[] res = namedJdbcTemplate.batchUpdate(sql, batch);


            System.out.println("Batch processed status: " + Arrays.toString(res));//Batch processed status: [-2, -2, -2]
            /*          >=1: The database successfully updated exactly that many rows.
                          0: No rows were affected.
                         -2: (SUCCESS_NO_INFO): The command was executed successfully, but the database/driver does not
                              know or choose to count (because of ?rewriteBatchedStatements=true) how many rows were affected.
                              */
            System.out.println("Batch processed: " + chunk.size() + " records (Index: " + i + ")");
        }
    }

    @Override
    public int insertWithTimestamp(TimestampEntity entity) {
        String sql = "INSERT INTO example_timestamp (DATA, CUR_TIMESTAMP) VALUES(?, ?)";
        return jdbcTemplate.update(sql, entity.getData(), entity.getCur_timestamp());
    }

    @Override
    public int insertWithDbCurrentTime(String data) {
        // Letting the Database handle the timestamp generation (Query 3)
        String sql = "INSERT INTO example_timestamp (DATA, CUR_TIMESTAMP) VALUES(?, CURRENT_TIMESTAMP(5))";
        return jdbcTemplate.update(sql, data);
    }

    @Override
    public int insertWithMapParams(Map<Integer, Object> params) {
        String sql = "INSERT INTO example_timestamp (DATA, CUR_TIMESTAMP) VALUES(?, CURRENT_TIMESTAMP(5))";
        return jdbcTemplate.update(sql, (PreparedStatement ps) -> {
            for (Map.Entry<Integer, Object> entry : params.entrySet()) {
                ps.setObject(entry.getKey(), entry.getValue());
            }
        });
    }
}